# Base image
FROM node:alpine3.10

WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app will run on
EXPOSE 80

# Define the command to run the application
CMD ["node", "app.js"]

